//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace pos13_app.pos13_app_services {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstUserController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data")]
    public partial class MstUserController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FullNameField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstTableController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstTableController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private System.Nullable<int> LeftLocationField;
        
        private string TableCodeField;
        
        private int TableGroupIdField;
        
        private System.Nullable<int> TopLocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LeftLocation {
            get {
                return this.LeftLocationField;
            }
            set {
                if ((this.LeftLocationField.Equals(value) != true)) {
                    this.LeftLocationField = value;
                    this.RaisePropertyChanged("LeftLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableCode {
            get {
                return this.TableCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TableCodeField, value) != true)) {
                    this.TableCodeField = value;
                    this.RaisePropertyChanged("TableCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TableGroupId {
            get {
                return this.TableGroupIdField;
            }
            set {
                if ((this.TableGroupIdField.Equals(value) != true)) {
                    this.TableGroupIdField = value;
                    this.RaisePropertyChanged("TableGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TopLocation {
            get {
                return this.TopLocationField;
            }
            set {
                if ((this.TopLocationField.Equals(value) != true)) {
                    this.TopLocationField = value;
                    this.RaisePropertyChanged("TopLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstTableGroupController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstTableGroupController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime EntryDateTimeField;
        
        private int EntryUserIdField;
        
        private int IdField;
        
        private string TableGroupField;
        
        private System.DateTime UpdateDateTimeField;
        
        private int UpdateUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDateTime {
            get {
                return this.EntryDateTimeField;
            }
            set {
                if ((this.EntryDateTimeField.Equals(value) != true)) {
                    this.EntryDateTimeField = value;
                    this.RaisePropertyChanged("EntryDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntryUserId {
            get {
                return this.EntryUserIdField;
            }
            set {
                if ((this.EntryUserIdField.Equals(value) != true)) {
                    this.EntryUserIdField = value;
                    this.RaisePropertyChanged("EntryUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableGroup {
            get {
                return this.TableGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.TableGroupField, value) != true)) {
                    this.TableGroupField = value;
                    this.RaisePropertyChanged("TableGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDateTime {
            get {
                return this.UpdateDateTimeField;
            }
            set {
                if ((this.UpdateDateTimeField.Equals(value) != true)) {
                    this.UpdateDateTimeField = value;
                    this.RaisePropertyChanged("UpdateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserId {
            get {
                return this.UpdateUserIdField;
            }
            set {
                if ((this.UpdateUserIdField.Equals(value) != true)) {
                    this.UpdateUserIdField = value;
                    this.RaisePropertyChanged("UpdateUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrnSalesOrderController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class TrnSalesOrderController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal AmountField;
        
        private string AmountDescriptionField;
        
        private int CustomerIdField;
        
        private decimal GrossAmountField;
        
        private string GrossAmountDescriptionField;
        
        private int IdField;
        
        private string InvoiceStatusField;
        
        private string InvoiceTableIdField;
        
        private decimal LessAmountField;
        
        private string LessAmountDescriptionField;
        
        private System.Nullable<int> PaxField;
        
        private string PreparedByField;
        
        private string RemarksField;
        
        private int SalesAgentField;
        
        private System.DateTime SalesDateField;
        
        private string SalesNumberField;
        
        private string TableCodeField;
        
        private int TermIdField;
        
        private string TerminalField;
        
        private string TransactionDateField;
        
        private string UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountDescription {
            get {
                return this.AmountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountDescriptionField, value) != true)) {
                    this.AmountDescriptionField = value;
                    this.RaisePropertyChanged("AmountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrossAmount {
            get {
                return this.GrossAmountField;
            }
            set {
                if ((this.GrossAmountField.Equals(value) != true)) {
                    this.GrossAmountField = value;
                    this.RaisePropertyChanged("GrossAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrossAmountDescription {
            get {
                return this.GrossAmountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.GrossAmountDescriptionField, value) != true)) {
                    this.GrossAmountDescriptionField = value;
                    this.RaisePropertyChanged("GrossAmountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceStatus {
            get {
                return this.InvoiceStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceStatusField, value) != true)) {
                    this.InvoiceStatusField = value;
                    this.RaisePropertyChanged("InvoiceStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceTableId {
            get {
                return this.InvoiceTableIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceTableIdField, value) != true)) {
                    this.InvoiceTableIdField = value;
                    this.RaisePropertyChanged("InvoiceTableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LessAmount {
            get {
                return this.LessAmountField;
            }
            set {
                if ((this.LessAmountField.Equals(value) != true)) {
                    this.LessAmountField = value;
                    this.RaisePropertyChanged("LessAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LessAmountDescription {
            get {
                return this.LessAmountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LessAmountDescriptionField, value) != true)) {
                    this.LessAmountDescriptionField = value;
                    this.RaisePropertyChanged("LessAmountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Pax {
            get {
                return this.PaxField;
            }
            set {
                if ((this.PaxField.Equals(value) != true)) {
                    this.PaxField = value;
                    this.RaisePropertyChanged("Pax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreparedBy {
            get {
                return this.PreparedByField;
            }
            set {
                if ((object.ReferenceEquals(this.PreparedByField, value) != true)) {
                    this.PreparedByField = value;
                    this.RaisePropertyChanged("PreparedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesAgent {
            get {
                return this.SalesAgentField;
            }
            set {
                if ((this.SalesAgentField.Equals(value) != true)) {
                    this.SalesAgentField = value;
                    this.RaisePropertyChanged("SalesAgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SalesDate {
            get {
                return this.SalesDateField;
            }
            set {
                if ((this.SalesDateField.Equals(value) != true)) {
                    this.SalesDateField = value;
                    this.RaisePropertyChanged("SalesDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesNumber {
            get {
                return this.SalesNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesNumberField, value) != true)) {
                    this.SalesNumberField = value;
                    this.RaisePropertyChanged("SalesNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableCode {
            get {
                return this.TableCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TableCodeField, value) != true)) {
                    this.TableCodeField = value;
                    this.RaisePropertyChanged("TableCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TermId {
            get {
                return this.TermIdField;
            }
            set {
                if ((this.TermIdField.Equals(value) != true)) {
                    this.TermIdField = value;
                    this.RaisePropertyChanged("TermId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terminal {
            get {
                return this.TerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalField, value) != true)) {
                    this.TerminalField = value;
                    this.RaisePropertyChanged("Terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrnSalesOrderDetailController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class TrnSalesOrderDetailController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal AmountField;
        
        private string AmountDescriptionField;
        
        private decimal DiscountAmountField;
        
        private int DiscountIdField;
        
        private decimal DiscountRateField;
        
        private int IdField;
        
        private string ItemDescriptionField;
        
        private int ItemIdField;
        
        private decimal NetPriceField;
        
        private decimal PriceField;
        
        private string PriceDescriptionField;
        
        private decimal QuantityField;
        
        private string QuantityDescriptionField;
        
        private string SalesItemIdField;
        
        private string TaxField;
        
        private decimal TaxAmountField;
        
        private int TaxIdField;
        
        private decimal TaxRateField;
        
        private string UnitField;
        
        private int UnitIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmountDescription {
            get {
                return this.AmountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountDescriptionField, value) != true)) {
                    this.AmountDescriptionField = value;
                    this.RaisePropertyChanged("AmountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountAmount {
            get {
                return this.DiscountAmountField;
            }
            set {
                if ((this.DiscountAmountField.Equals(value) != true)) {
                    this.DiscountAmountField = value;
                    this.RaisePropertyChanged("DiscountAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscountId {
            get {
                return this.DiscountIdField;
            }
            set {
                if ((this.DiscountIdField.Equals(value) != true)) {
                    this.DiscountIdField = value;
                    this.RaisePropertyChanged("DiscountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountRate {
            get {
                return this.DiscountRateField;
            }
            set {
                if ((this.DiscountRateField.Equals(value) != true)) {
                    this.DiscountRateField = value;
                    this.RaisePropertyChanged("DiscountRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetPrice {
            get {
                return this.NetPriceField;
            }
            set {
                if ((this.NetPriceField.Equals(value) != true)) {
                    this.NetPriceField = value;
                    this.RaisePropertyChanged("NetPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceDescription {
            get {
                return this.PriceDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceDescriptionField, value) != true)) {
                    this.PriceDescriptionField = value;
                    this.RaisePropertyChanged("PriceDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityDescription {
            get {
                return this.QuantityDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityDescriptionField, value) != true)) {
                    this.QuantityDescriptionField = value;
                    this.RaisePropertyChanged("QuantityDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesItemId {
            get {
                return this.SalesItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesItemIdField, value) != true)) {
                    this.SalesItemIdField = value;
                    this.RaisePropertyChanged("SalesItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxField, value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmount {
            get {
                return this.TaxAmountField;
            }
            set {
                if ((this.TaxAmountField.Equals(value) != true)) {
                    this.TaxAmountField = value;
                    this.RaisePropertyChanged("TaxAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaxId {
            get {
                return this.TaxIdField;
            }
            set {
                if ((this.TaxIdField.Equals(value) != true)) {
                    this.TaxIdField = value;
                    this.RaisePropertyChanged("TaxId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxRate {
            get {
                return this.TaxRateField;
            }
            set {
                if ((this.TaxRateField.Equals(value) != true)) {
                    this.TaxRateField = value;
                    this.RaisePropertyChanged("TaxRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitId {
            get {
                return this.UnitIdField;
            }
            set {
                if ((this.UnitIdField.Equals(value) != true)) {
                    this.UnitIdField = value;
                    this.RaisePropertyChanged("UnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstItemGroupController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstItemGroupController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime EntryDateTimeField;
        
        private int EntryUserIdField;
        
        private int IdField;
        
        private string ImagePathField;
        
        private bool IslockedField;
        
        private string ItemGroupField;
        
        private string KitchenReportField;
        
        private System.DateTime UpdateDateTimeField;
        
        private int UpdateUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDateTime {
            get {
                return this.EntryDateTimeField;
            }
            set {
                if ((this.EntryDateTimeField.Equals(value) != true)) {
                    this.EntryDateTimeField = value;
                    this.RaisePropertyChanged("EntryDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntryUserId {
            get {
                return this.EntryUserIdField;
            }
            set {
                if ((this.EntryUserIdField.Equals(value) != true)) {
                    this.EntryUserIdField = value;
                    this.RaisePropertyChanged("EntryUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Islocked {
            get {
                return this.IslockedField;
            }
            set {
                if ((this.IslockedField.Equals(value) != true)) {
                    this.IslockedField = value;
                    this.RaisePropertyChanged("Islocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemGroup {
            get {
                return this.ItemGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemGroupField, value) != true)) {
                    this.ItemGroupField = value;
                    this.RaisePropertyChanged("ItemGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KitchenReport {
            get {
                return this.KitchenReportField;
            }
            set {
                if ((object.ReferenceEquals(this.KitchenReportField, value) != true)) {
                    this.KitchenReportField = value;
                    this.RaisePropertyChanged("KitchenReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDateTime {
            get {
                return this.UpdateDateTimeField;
            }
            set {
                if ((this.UpdateDateTimeField.Equals(value) != true)) {
                    this.UpdateDateTimeField = value;
                    this.RaisePropertyChanged("UpdateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserId {
            get {
                return this.UpdateUserIdField;
            }
            set {
                if ((this.UpdateUserIdField.Equals(value) != true)) {
                    this.UpdateUserIdField = value;
                    this.RaisePropertyChanged("UpdateUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstItemController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstItemController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AliasField;
        
        private string BarcodeField;
        
        private string CategoryField;
        
        private decimal CostField;
        
        private string GenericNameField;
        
        private int IdField;
        
        private string ImagePathField;
        
        private bool IsLockedField;
        
        private string ItemCodeField;
        
        private string ItemDescriptionField;
        
        private int ItemGroupIdField;
        
        private decimal MarkUpField;
        
        private int OutTaxIdField;
        
        private decimal PriceField;
        
        private int SalesAccountIdField;
        
        private int UnitIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenericName {
            get {
                return this.GenericNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GenericNameField, value) != true)) {
                    this.GenericNameField = value;
                    this.RaisePropertyChanged("GenericName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemGroupId {
            get {
                return this.ItemGroupIdField;
            }
            set {
                if ((this.ItemGroupIdField.Equals(value) != true)) {
                    this.ItemGroupIdField = value;
                    this.RaisePropertyChanged("ItemGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarkUp {
            get {
                return this.MarkUpField;
            }
            set {
                if ((this.MarkUpField.Equals(value) != true)) {
                    this.MarkUpField = value;
                    this.RaisePropertyChanged("MarkUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OutTaxId {
            get {
                return this.OutTaxIdField;
            }
            set {
                if ((this.OutTaxIdField.Equals(value) != true)) {
                    this.OutTaxIdField = value;
                    this.RaisePropertyChanged("OutTaxId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesAccountId {
            get {
                return this.SalesAccountIdField;
            }
            set {
                if ((this.SalesAccountIdField.Equals(value) != true)) {
                    this.SalesAccountIdField = value;
                    this.RaisePropertyChanged("SalesAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitId {
            get {
                return this.UnitIdField;
            }
            set {
                if ((this.UnitIdField.Equals(value) != true)) {
                    this.UnitIdField = value;
                    this.RaisePropertyChanged("UnitId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstItem", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Models")]
    public partial class MstItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string ItemCodeField;
        
        private string ItemDescriptionField;
        
        private int OutTaxIdField;
        
        private decimal PriceField;
        
        private decimal VatRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OutTaxId {
            get {
                return this.OutTaxIdField;
            }
            set {
                if ((this.OutTaxIdField.Equals(value) != true)) {
                    this.OutTaxIdField = value;
                    this.RaisePropertyChanged("OutTaxId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VatRate {
            get {
                return this.VatRateField;
            }
            set {
                if ((this.VatRateField.Equals(value) != true)) {
                    this.VatRateField = value;
                    this.RaisePropertyChanged("VatRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstUnitController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstUnitController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string UnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstTaxController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstTaxController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AccountIdField;
        
        private string CodeField;
        
        private int IdField;
        
        private decimal RateField;
        
        private string TaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxField, value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstDiscountController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstDiscountController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime DateEndField;
        
        private System.DateTime DateStartField;
        
        private bool DayFriField;
        
        private bool DayMonField;
        
        private bool DaySatField;
        
        private bool DaySunField;
        
        private bool DayThuField;
        
        private bool DayTueField;
        
        private bool DayWedField;
        
        private string DiscountField;
        
        private decimal DiscountRateField;
        
        private System.DateTime EntryDateTimeField;
        
        private int EntryUserIdField;
        
        private int IdField;
        
        private bool IsDateScheduledField;
        
        private bool IsDayScheduledField;
        
        private bool IsLockedField;
        
        private bool IsTimeScheduledField;
        
        private bool IsVatExempField;
        
        private bool IsVatExemptField;
        
        private System.DateTime TimeEndField;
        
        private System.DateTime TimeStartField;
        
        private System.DateTime UpdateDateTimeField;
        
        private int UpdateUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEnd {
            get {
                return this.DateEndField;
            }
            set {
                if ((this.DateEndField.Equals(value) != true)) {
                    this.DateEndField = value;
                    this.RaisePropertyChanged("DateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateStart {
            get {
                return this.DateStartField;
            }
            set {
                if ((this.DateStartField.Equals(value) != true)) {
                    this.DateStartField = value;
                    this.RaisePropertyChanged("DateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DayFri {
            get {
                return this.DayFriField;
            }
            set {
                if ((this.DayFriField.Equals(value) != true)) {
                    this.DayFriField = value;
                    this.RaisePropertyChanged("DayFri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DayMon {
            get {
                return this.DayMonField;
            }
            set {
                if ((this.DayMonField.Equals(value) != true)) {
                    this.DayMonField = value;
                    this.RaisePropertyChanged("DayMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DaySat {
            get {
                return this.DaySatField;
            }
            set {
                if ((this.DaySatField.Equals(value) != true)) {
                    this.DaySatField = value;
                    this.RaisePropertyChanged("DaySat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DaySun {
            get {
                return this.DaySunField;
            }
            set {
                if ((this.DaySunField.Equals(value) != true)) {
                    this.DaySunField = value;
                    this.RaisePropertyChanged("DaySun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DayThu {
            get {
                return this.DayThuField;
            }
            set {
                if ((this.DayThuField.Equals(value) != true)) {
                    this.DayThuField = value;
                    this.RaisePropertyChanged("DayThu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DayTue {
            get {
                return this.DayTueField;
            }
            set {
                if ((this.DayTueField.Equals(value) != true)) {
                    this.DayTueField = value;
                    this.RaisePropertyChanged("DayTue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DayWed {
            get {
                return this.DayWedField;
            }
            set {
                if ((this.DayWedField.Equals(value) != true)) {
                    this.DayWedField = value;
                    this.RaisePropertyChanged("DayWed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountField, value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountRate {
            get {
                return this.DiscountRateField;
            }
            set {
                if ((this.DiscountRateField.Equals(value) != true)) {
                    this.DiscountRateField = value;
                    this.RaisePropertyChanged("DiscountRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDateTime {
            get {
                return this.EntryDateTimeField;
            }
            set {
                if ((this.EntryDateTimeField.Equals(value) != true)) {
                    this.EntryDateTimeField = value;
                    this.RaisePropertyChanged("EntryDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntryUserId {
            get {
                return this.EntryUserIdField;
            }
            set {
                if ((this.EntryUserIdField.Equals(value) != true)) {
                    this.EntryUserIdField = value;
                    this.RaisePropertyChanged("EntryUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDateScheduled {
            get {
                return this.IsDateScheduledField;
            }
            set {
                if ((this.IsDateScheduledField.Equals(value) != true)) {
                    this.IsDateScheduledField = value;
                    this.RaisePropertyChanged("IsDateScheduled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDayScheduled {
            get {
                return this.IsDayScheduledField;
            }
            set {
                if ((this.IsDayScheduledField.Equals(value) != true)) {
                    this.IsDayScheduledField = value;
                    this.RaisePropertyChanged("IsDayScheduled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTimeScheduled {
            get {
                return this.IsTimeScheduledField;
            }
            set {
                if ((this.IsTimeScheduledField.Equals(value) != true)) {
                    this.IsTimeScheduledField = value;
                    this.RaisePropertyChanged("IsTimeScheduled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVatExemp {
            get {
                return this.IsVatExempField;
            }
            set {
                if ((this.IsVatExempField.Equals(value) != true)) {
                    this.IsVatExempField = value;
                    this.RaisePropertyChanged("IsVatExemp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVatExempt {
            get {
                return this.IsVatExemptField;
            }
            set {
                if ((this.IsVatExemptField.Equals(value) != true)) {
                    this.IsVatExemptField = value;
                    this.RaisePropertyChanged("IsVatExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeEnd {
            get {
                return this.TimeEndField;
            }
            set {
                if ((this.TimeEndField.Equals(value) != true)) {
                    this.TimeEndField = value;
                    this.RaisePropertyChanged("TimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStart {
            get {
                return this.TimeStartField;
            }
            set {
                if ((this.TimeStartField.Equals(value) != true)) {
                    this.TimeStartField = value;
                    this.RaisePropertyChanged("TimeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDateTime {
            get {
                return this.UpdateDateTimeField;
            }
            set {
                if ((this.UpdateDateTimeField.Equals(value) != true)) {
                    this.UpdateDateTimeField = value;
                    this.RaisePropertyChanged("UpdateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdateUserId {
            get {
                return this.UpdateUserIdField;
            }
            set {
                if ((this.UpdateUserIdField.Equals(value) != true)) {
                    this.UpdateUserIdField = value;
                    this.RaisePropertyChanged("UpdateUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstCustomerController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstCustomerController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CustomerField;
        
        private int IdField;
        
        private string TermField;
        
        private int TermIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Term {
            get {
                return this.TermField;
            }
            set {
                if ((object.ReferenceEquals(this.TermField, value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TermId {
            get {
                return this.TermIdField;
            }
            set {
                if ((this.TermIdField.Equals(value) != true)) {
                    this.TermIdField = value;
                    this.RaisePropertyChanged("TermId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MstTermController", Namespace="http://schemas.datacontract.org/2004/07/pos13_app_data.Controllers")]
    public partial class MstTermController : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string TermField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Term {
            get {
                return this.TermField;
            }
            set {
                if ((object.ReferenceEquals(this.TermField, value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="pos13_app_services.IPos13_app_service")]
    public interface IPos13_app_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/getUserName", ReplyAction="http://tempuri.org/IPos13_app_service/getUserNameResponse")]
        System.Threading.Tasks.Task<string> getUserNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/getUserId", ReplyAction="http://tempuri.org/IPos13_app_service/getUserIdResponse")]
        System.Threading.Tasks.Task<int> getUserIdAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/isLogin", ReplyAction="http://tempuri.org/IPos13_app_service/isLoginResponse")]
        System.Threading.Tasks.Task<bool> isLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/UserCombo", ReplyAction="http://tempuri.org/IPos13_app_service/UserComboResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstUserController>> UserComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/GetMstTable", ReplyAction="http://tempuri.org/IPos13_app_service/GetMstTableResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTableController>> GetMstTableAsync(int TableGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/GetMstTableGroup", ReplyAction="http://tempuri.org/IPos13_app_service/GetMstTableGroupResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTableGroupController>> GetMstTableGroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/MinTableGroupId", ReplyAction="http://tempuri.org/IPos13_app_service/MinTableGroupIdResponse")]
        System.Threading.Tasks.Task<int> MinTableGroupIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/TrnSalesOrderListSF1", ReplyAction="http://tempuri.org/IPos13_app_service/TrnSalesOrderListSF1Response")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderController>> TrnSalesOrderListSF1Async(System.DateTime SalesDate, string InvoiceStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/TrnSalesOrderDetail", ReplyAction="http://tempuri.org/IPos13_app_service/TrnSalesOrderDetailResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderController>> TrnSalesOrderDetailAsync(int InvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/TrnSalesOrderDetailZero", ReplyAction="http://tempuri.org/IPos13_app_service/TrnSalesOrderDetailZeroResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderController>> TrnSalesOrderDetailZeroAsync(int InvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/GetTableInvoiceId", ReplyAction="http://tempuri.org/IPos13_app_service/GetTableInvoiceIdResponse")]
        System.Threading.Tasks.Task<int> GetTableInvoiceIdAsync(System.DateTime SalesDate, int TableId, string InvoiceStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/TrnSalesOrderDetailItem", ReplyAction="http://tempuri.org/IPos13_app_service/TrnSalesOrderDetailItemResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderDetailController>> TrnSalesOrderDetailItemAsync(int SalesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/TrnSalesTrnSalesOrderDetailItemDetail", ReplyAction="http://tempuri.org/IPos13_app_service/TrnSalesTrnSalesOrderDetailItemDetailRespon" +
            "se")]
        System.Threading.Tasks.Task<pos13_app.pos13_app_services.TrnSalesOrderDetailController> TrnSalesTrnSalesOrderDetailItemDetailAsync(int InvoiceLineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/GetMstItemGroup", ReplyAction="http://tempuri.org/IPos13_app_service/GetMstItemGroupResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstItemGroupController>> GetMstItemGroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/MinItemGroupId", ReplyAction="http://tempuri.org/IPos13_app_service/MinItemGroupIdResponse")]
        System.Threading.Tasks.Task<int> MinItemGroupIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/GetMstItem", ReplyAction="http://tempuri.org/IPos13_app_service/GetMstItemResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstItemController>> GetMstItemAsync(int ItemGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/ItemComboBox", ReplyAction="http://tempuri.org/IPos13_app_service/ItemComboBoxResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstItem>> ItemComboBoxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/UnitCombo", ReplyAction="http://tempuri.org/IPos13_app_service/UnitComboResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstUnitController>> UnitComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/TaxCombo", ReplyAction="http://tempuri.org/IPos13_app_service/TaxComboResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTaxController>> TaxComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/DiscountCombo", ReplyAction="http://tempuri.org/IPos13_app_service/DiscountComboResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstDiscountController>> DiscountComboAsync(System.DateTime SalesDate, int ItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/CustomerCombo", ReplyAction="http://tempuri.org/IPos13_app_service/CustomerComboResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstCustomerController>> CustomerComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/TermCombo", ReplyAction="http://tempuri.org/IPos13_app_service/TermComboResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTermController>> TermComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/InserSalesOrder", ReplyAction="http://tempuri.org/IPos13_app_service/InserSalesOrderResponse")]
        System.Threading.Tasks.Task InserSalesOrderAsync(
                    int Id, 
                    int PeriodId, 
                    System.DateTime SalesDate, 
                    string SalesNumber, 
                    string ManualInvoiceNumber, 
                    decimal Amount, 
                    int TableId, 
                    int CustomerId, 
                    int AccountId, 
                    int TermId, 
                    int DiscountId, 
                    string SeniorCitizenId, 
                    string SeniorCitizenName, 
                    int SeniorCitizenAge, 
                    string Remarks, 
                    int SalesAgent, 
                    int TerminalId, 
                    int PreparedBy, 
                    int CheckedBy, 
                    int ApprovedBy, 
                    bool IsLocked, 
                    bool IsCancelled, 
                    decimal PaidAmount, 
                    decimal CreditAmount, 
                    decimal DebitAmount, 
                    decimal BalanceAmount, 
                    int EntryUserId, 
                    System.DateTime EntryDateTime, 
                    int UpdateUserId, 
                    System.DateTime UpdateDateTime, 
                    int Pax, 
                    string Exec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/UpdateInvoiceTotalAmount", ReplyAction="http://tempuri.org/IPos13_app_service/UpdateInvoiceTotalAmountResponse")]
        System.Threading.Tasks.Task UpdateInvoiceTotalAmountAsync(int InvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/DeleteSales", ReplyAction="http://tempuri.org/IPos13_app_service/DeleteSalesResponse")]
        System.Threading.Tasks.Task DeleteSalesAsync(int SalesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/InsertSalesOrderLine", ReplyAction="http://tempuri.org/IPos13_app_service/InsertSalesOrderLineResponse")]
        System.Threading.Tasks.Task InsertSalesOrderLineAsync(
                    int SalesLineId, 
                    int SalesId, 
                    int ItemId, 
                    int UnitId, 
                    decimal Price, 
                    int DiscountId, 
                    decimal DiscountRate, 
                    decimal DiscountAmount, 
                    decimal NetPrice, 
                    decimal Quantity, 
                    decimal Amount, 
                    int TaxId, 
                    decimal TaxRate, 
                    decimal TaxAmount, 
                    int SalesAccountId, 
                    int AssetAccountId, 
                    int CostAccountId, 
                    int TaxAccountId, 
                    System.DateTime SalesLineTimeStamp, 
                    int UserId, 
                    string Preparation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPos13_app_service/DeleteSalesLine", ReplyAction="http://tempuri.org/IPos13_app_service/DeleteSalesLineResponse")]
        System.Threading.Tasks.Task DeleteSalesLineAsync(int SalesLineId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPos13_app_serviceChannel : pos13_app.pos13_app_services.IPos13_app_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Pos13_app_serviceClient : System.ServiceModel.ClientBase<pos13_app.pos13_app_services.IPos13_app_service>, pos13_app.pos13_app_services.IPos13_app_service {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Pos13_app_serviceClient() : 
                base(Pos13_app_serviceClient.GetDefaultBinding(), Pos13_app_serviceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPos13_app_service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pos13_app_serviceClient(EndpointConfiguration endpointConfiguration) : 
                base(Pos13_app_serviceClient.GetBindingForEndpoint(endpointConfiguration), Pos13_app_serviceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pos13_app_serviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Pos13_app_serviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pos13_app_serviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Pos13_app_serviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Pos13_app_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> getUserNameAsync(int id) {
            return base.Channel.getUserNameAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> getUserIdAsync(string username, string password) {
            return base.Channel.getUserIdAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> isLoginAsync(string username, string password) {
            return base.Channel.isLoginAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstUserController>> UserComboAsync() {
            return base.Channel.UserComboAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTableController>> GetMstTableAsync(int TableGroupId) {
            return base.Channel.GetMstTableAsync(TableGroupId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTableGroupController>> GetMstTableGroupAsync() {
            return base.Channel.GetMstTableGroupAsync();
        }
        
        public System.Threading.Tasks.Task<int> MinTableGroupIdAsync() {
            return base.Channel.MinTableGroupIdAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderController>> TrnSalesOrderListSF1Async(System.DateTime SalesDate, string InvoiceStatus) {
            return base.Channel.TrnSalesOrderListSF1Async(SalesDate, InvoiceStatus);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderController>> TrnSalesOrderDetailAsync(int InvoiceId) {
            return base.Channel.TrnSalesOrderDetailAsync(InvoiceId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderController>> TrnSalesOrderDetailZeroAsync(int InvoiceId) {
            return base.Channel.TrnSalesOrderDetailZeroAsync(InvoiceId);
        }
        
        public System.Threading.Tasks.Task<int> GetTableInvoiceIdAsync(System.DateTime SalesDate, int TableId, string InvoiceStatus) {
            return base.Channel.GetTableInvoiceIdAsync(SalesDate, TableId, InvoiceStatus);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.TrnSalesOrderDetailController>> TrnSalesOrderDetailItemAsync(int SalesId) {
            return base.Channel.TrnSalesOrderDetailItemAsync(SalesId);
        }
        
        public System.Threading.Tasks.Task<pos13_app.pos13_app_services.TrnSalesOrderDetailController> TrnSalesTrnSalesOrderDetailItemDetailAsync(int InvoiceLineId) {
            return base.Channel.TrnSalesTrnSalesOrderDetailItemDetailAsync(InvoiceLineId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstItemGroupController>> GetMstItemGroupAsync() {
            return base.Channel.GetMstItemGroupAsync();
        }
        
        public System.Threading.Tasks.Task<int> MinItemGroupIdAsync() {
            return base.Channel.MinItemGroupIdAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstItemController>> GetMstItemAsync(int ItemGroupId) {
            return base.Channel.GetMstItemAsync(ItemGroupId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstItem>> ItemComboBoxAsync() {
            return base.Channel.ItemComboBoxAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstUnitController>> UnitComboAsync() {
            return base.Channel.UnitComboAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTaxController>> TaxComboAsync() {
            return base.Channel.TaxComboAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstDiscountController>> DiscountComboAsync(System.DateTime SalesDate, int ItemId) {
            return base.Channel.DiscountComboAsync(SalesDate, ItemId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstCustomerController>> CustomerComboAsync() {
            return base.Channel.CustomerComboAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<pos13_app.pos13_app_services.MstTermController>> TermComboAsync() {
            return base.Channel.TermComboAsync();
        }
        
        public System.Threading.Tasks.Task InserSalesOrderAsync(
                    int Id, 
                    int PeriodId, 
                    System.DateTime SalesDate, 
                    string SalesNumber, 
                    string ManualInvoiceNumber, 
                    decimal Amount, 
                    int TableId, 
                    int CustomerId, 
                    int AccountId, 
                    int TermId, 
                    int DiscountId, 
                    string SeniorCitizenId, 
                    string SeniorCitizenName, 
                    int SeniorCitizenAge, 
                    string Remarks, 
                    int SalesAgent, 
                    int TerminalId, 
                    int PreparedBy, 
                    int CheckedBy, 
                    int ApprovedBy, 
                    bool IsLocked, 
                    bool IsCancelled, 
                    decimal PaidAmount, 
                    decimal CreditAmount, 
                    decimal DebitAmount, 
                    decimal BalanceAmount, 
                    int EntryUserId, 
                    System.DateTime EntryDateTime, 
                    int UpdateUserId, 
                    System.DateTime UpdateDateTime, 
                    int Pax, 
                    string Exec) {
            return base.Channel.InserSalesOrderAsync(Id, PeriodId, SalesDate, SalesNumber, ManualInvoiceNumber, Amount, TableId, CustomerId, AccountId, TermId, DiscountId, SeniorCitizenId, SeniorCitizenName, SeniorCitizenAge, Remarks, SalesAgent, TerminalId, PreparedBy, CheckedBy, ApprovedBy, IsLocked, IsCancelled, PaidAmount, CreditAmount, DebitAmount, BalanceAmount, EntryUserId, EntryDateTime, UpdateUserId, UpdateDateTime, Pax, Exec);
        }
        
        public System.Threading.Tasks.Task UpdateInvoiceTotalAmountAsync(int InvoiceId) {
            return base.Channel.UpdateInvoiceTotalAmountAsync(InvoiceId);
        }
        
        public System.Threading.Tasks.Task DeleteSalesAsync(int SalesId) {
            return base.Channel.DeleteSalesAsync(SalesId);
        }
        
        public System.Threading.Tasks.Task InsertSalesOrderLineAsync(
                    int SalesLineId, 
                    int SalesId, 
                    int ItemId, 
                    int UnitId, 
                    decimal Price, 
                    int DiscountId, 
                    decimal DiscountRate, 
                    decimal DiscountAmount, 
                    decimal NetPrice, 
                    decimal Quantity, 
                    decimal Amount, 
                    int TaxId, 
                    decimal TaxRate, 
                    decimal TaxAmount, 
                    int SalesAccountId, 
                    int AssetAccountId, 
                    int CostAccountId, 
                    int TaxAccountId, 
                    System.DateTime SalesLineTimeStamp, 
                    int UserId, 
                    string Preparation) {
            return base.Channel.InsertSalesOrderLineAsync(SalesLineId, SalesId, ItemId, UnitId, Price, DiscountId, DiscountRate, DiscountAmount, NetPrice, Quantity, Amount, TaxId, TaxRate, TaxAmount, SalesAccountId, AssetAccountId, CostAccountId, TaxAccountId, SalesLineTimeStamp, UserId, Preparation);
        }
        
        public System.Threading.Tasks.Task DeleteSalesLineAsync(int SalesLineId) {
            return base.Channel.DeleteSalesLineAsync(SalesLineId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPos13_app_service)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPos13_app_service)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:20644/pos13_app_services.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Pos13_app_serviceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPos13_app_service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Pos13_app_serviceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPos13_app_service);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IPos13_app_service,
        }
    }
}
